// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreSemanticProvenance } from "./CoreSemanticProvenance";

export type CoreNavigationIdentity = { provider: CoreSemanticProvenance, providerEpoch: number, sessionInstanceId: number, };
