// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreNavigationIdentity } from "./CoreNavigationIdentity";
import type { CoreSemanticProvenance } from "./CoreSemanticProvenance";
import type { CoreSourceSpan } from "./CoreSourceSpan";

export type CorePassageLocation = { navigationIdentity?: CoreNavigationIdentity, passageId: string, passageName: string, provenance: CoreSemanticProvenance, resultKey: string, revision: number, span: CoreSourceSpan, storyId: string, };
