// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Patch } from "./Patch";
import type { StoryTagRename } from "./StoryTagRename";

export type PatchBatch = { label: string, patches: Array<Patch>, storyTagRename?: StoryTagRename, transactionId: bigint, };
